### ISSUE TITLE
I can't start the elasticsearch script...

### ISSUE THREAD

**Issue by minemax-ua** [delvedor/fastify-example#17]
`npm run elasticsearch

> fastify-app-example@1.0.0 elasticsearch
> ./scripts/elasticsearch.sh

./scripts/elasticsearch.sh: line 3: exec: docker: not found`

**Comment by minemax-ua** [comment]
This is supposed to be an example for learning Fastify, not promoting your company, really...

**Comment by rommelandrea** [comment]
@minemax-ua you need to install Docker on your PC

**Comment by delvedor** [comment]
The script had a bug, fixed in https://github.com/delvedor/fastify-example/pull/18.
